### ISSUE TITLE
🕷 [Search] not working as expected - no wildcard search

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-server#22]
Search returns weird values, which do not corespond to search term.

The Problem is that the search requires full terms.
- Searching for "Geset" will resullt in no Results at all,
- but searching for "Gesetz" will show Results

**Comment by ManAnRuck** [comment]
@ulfgebhardt https://jira.mongodb.org/browse/SERVER-15090
ist wohl mit mongodb so leider nicht wirklich realisierbar. wir könnten auf das Gewichten verzichten und das eine nicht empfohlene RegExp Suchmethode umsteigen. Alternative wäre noch einen Elasticsearch docker aufzusetzen
